[build]
  command = ""
  publish = "."

# 1. Root -> Main App
[[redirects]]
  from = "/"
  to = "/app/index.html"
  status = 200
  force = true

# 4. Cache Headers
[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/app/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
