[build]
  command = ""
  publish = "."

# Redirect everything to the single page app entry point
[[redirects]]
  from = "/*"
  to = "/app/index.html"
  status = 200
  force = true

# Cache
[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
